# Generated by Django 4.2.1 on 2024-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_alter_review_rating_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
