# Generated by Django 4.2.1 on 2024-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0014_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
