# Generated by Django 4.2.1 on 2024-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0015_reservation_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='dish',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
