# Generated by Django 4.2.1 on 2024-06-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0017_delete_category_delete_women_remove_dish_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
