# Generated by Django 4.2.1 on 2024-06-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0020_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='women.dish'),
        ),
    ]
