# Generated by Django 4.2.1 on 2024-06-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0021_favorites_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='name',
        ),
    ]
