# Generated by Django 4.2.1 on 2024-12-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0022_remove_favorites_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Women',
        ),
    ]
